spring:
    datasource:
        url: jdbc:mysql://localhost:3306/expense_tracker
        username: kuro
        password: passer
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        #        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true

    application:
        name: expense-tracker

server:
    port: 8081
api:
    prefix: api/v1
logging:
    level:
        #
        org.springframework.security: TRACE

security:
    jwt:
        secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
        # 1h in millisecond
        expiration-time: 3600000