spring:
    datasource:
        url: jdbc:mysql://${SPRING_MYSQL_HOST}:3306/${SPRING_MYSQL_DB_NAME}
        username: ${SPRING_MYSQL_USERNAME}
        password: ${SPRING_MYSQL_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        #        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update

    mail:
        host: smtp.gmail.com
        port: 587
        username: ${SPRING_GMAIL_USERNAME}
        password: ${SPRING_GMAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        required: true
                        enable: true
    application:
        name: expense-tracker

server:
    port: 8081

api:
    prefix: api/v1

bert-cat-api:
    url: ${SPRING_BERT_API_ENDPOINT}

logging:
    level:
        com.kuro: INFO
security:
    jwt:
        secret-key: ${SPRING_JWT_SECRET_KEY}
        # 1h in millisecond
        expiration-time: 3600000
    email-confirmation:
        expiration-time: 2 # in hours

config:
    app-name: K.E-Tracker

cors:
    allowedOrigins: ${SPRING_CORS_ALLOWED_ORIGINS}

