spring:
    jpa:
#        hibernate:
#            ddl-auto: create-drop
        show-sql: false

logging:
    level:
        root: WARN
        com.kuro: INFO
security:
    jwt:
        # 24h in millisecond
        expiration-time: 84600000