spring:
    datasource:
        url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DB_NAME}
        username: ${MYSQL_USERNAME}
        password: ${MYSQL_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        #        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update

    mail:
        host: smtp.gmail.com
        port: 587
        username: ${GMAIL_USERNAME}
        password: ${GMAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        required: true
                        enable: true
    application:
        name: expense-tracker

server:
    port: 8081

api:
    prefix: api/v1

logging:
    level:
        com.kuro: INFO
security:
    jwt:
        secret-key: ${JWT_SECRET_KEY}
        # 1h in millisecond
        expiration-time: 3600000
    email-confirmation:
        expiration-time: 2 # in hours

config:
    app-name: Kuro Expense Tracker