spring:
    jpa:
#        hibernate:
#            ddl-auto: create-drop
        show-sql: false
bert-cat-api:
    url: "http://localhost:8082/api/v1/categorize/"

logging:
    level:
        root: WARN
        com.kuro: INFO
security:
    jwt:
        # 24h in millisecond
        expiration-time: 84600000

cors:
    allowedOrigins: http://localhost:8100