spring:
    datasource:
        url: jdbc:mysql://localhost:3307/expense_tracker_test
        username: kuro
        password: passer
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
#        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true

    application:
        name: expense-tracker
api:
    prefix: api/v1