services:
    mysql:
        container_name: 'spring-mysql'
        image: 'mysql:latest'
        environment:
            - 'MYSQL_DATABASE=expense_tracker'
            - 'MYSQL_PASSWORD=passer'
            - 'MYSQL_ROOT_PASSWORD=passer'
            - 'MYSQL_USER=kuro'
        ports:
            - '3306:3306'
        volumes:
            - my-db:/var/lib/mysql
#    mysql-test:
#        container_name: 'spring-mysql-test'
#        image: 'mysql:latest'
#        environment:
#            - 'MYSQL_DATABASE=expense_tracker_test'
#            - 'MYSQL_PASSWORD=passer'
#            - 'MYSQL_ROOT_PASSWORD=passer'
#            - 'MYSQL_USER=kuro'
#        ports:
#            - '3307:3306'

volumes:
    my-db: