services:
    mysql:
        container_name: 'guide-mysql'
        image: 'mysql:latest'
        environment:
            - 'MYSQL_DATABASE=expense-tracker'
            - 'MYSQL_PASSWORD=secret'
            - 'MYSQL_ROOT_PASSWORD=secret'
            - 'MYSQL_USER=kuro'
        ports:
            - '3306:3306'
        volumes:
            - my-db:/var/lib/mysql
    mysql-workbench:
        image: lscr.io/linuxserver/mysql-workbench:latest
        container_name: mysql-workbench
        cap_add:
            - IPC_LOCK
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        volumes:
            - /var/lib/mysql-workbench:/config
        ports:
            - 3000:3000
            - 3001:3001
        restart: unless-stopped

volumes:
    my-db: